apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: iris
  predictors:
    - componentSpecs:
        - spec:
            # We are setting high failureThreshold as installing conda dependencies
            # can take long time and we want to avoid k8s killing the container prematurely
            containers:
              - name: classifier
                image: seldonio/mlflowserver:1.14.0-dev
                livenessProbe:
                  initialDelaySeconds: 120
                  failureThreshold: 200
                  periodSeconds: 5
                  successThreshold: 1
                  httpGet:
                    path: /health/ping
                    port: http
                    scheme: HTTP
                readinessProbe:
                  initialDelaySeconds: 120
                  failureThreshold: 200
                  periodSeconds: 5
                  successThreshold: 1
                  httpGet:
                    path: /health/ping
                    port: http
                    scheme: HTTP
      graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://mlflow/0/dab4c4585f194fd688e46c9933de907a/artifacts/pymodel
        envSecretRefName: bpk-seldon-init-container-secret
        #      envSecretRefName: seldon-init-container-secret
        name: classifier
      name: iris
      replicas: 1
