apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: "1.3.2"
  manifests:
    - URL: https://github.com/knative/eventing/releases/download/knative-v${VERSION}/eventing.yaml
    - URL: https://github.com/knative/eventing/releases/download/knative-v${VERSION}/eventing-post-install-jobs.yaml
